<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-12-02 10:49

$extensionPath = t3lib_extMgm::extPath('ics_gmap3_hierarchical_taglist');
$extensionClassesPath = t3lib_extMgm::extPath('ics_gmap3_hierarchical_taglist') . 'Classes/';
return array(
	'tx_icsgmap3hierarchicaltaglist_provider' => $extensionClassesPath . 'class.tx_icsgmap3hierarchicaltaglist_provider.php',
);
?>