<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-06-16 17:57

$extensionPath = t3lib_extMgm::extPath('ics_gmap3_ttaddress');
$extensionClassesPath = t3lib_extMgm::extPath('ics_gmap3_ttaddress') . 'classes/';
return array(
	'tx_icsgmap3ttaddress_provider' => $extensionClassesPath . 'class.tx_icsgmap3ttaddress_provider.php',
);
?>