<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-01-17 11:03

$extensionPath = t3lib_extMgm::extPath('ics_gmap3_datalist');
$extensionClassesPath = t3lib_extMgm::extPath('ics_gmap3_datalist') . 'Classes/';
return array(
	'tx_icsgmap3datalist_provider' => $extensionClassesPath . 'class.tx_icsgmap3datalist_provider.php',
);
?>