<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-01-17 11:03

$extensionPath = t3lib_extMgm::extPath('ics_gmap3_searchbox');
$extensionClassesPath = t3lib_extMgm::extPath('ics_gmap3_searchbox') . 'Classes/';
return array(
	'tx_icsgmap3searchbox_provider' => $extensionClassesPath . 'class.tx_icsgmap3searchbox_provider.php',
);
?>