<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-06-22 10:07

$extensionPath = t3lib_extMgm::extPath('ics_gmap3');
$extensionClassesPath = t3lib_extMgm::extPath('ics_gmap3') . 'Classes/';
return array(
	'tx_icsgmap3_iprovider' => $extensionClassesPath . 'interface.tx_icsgmap3_iprovider.php',
	'tx_icsgmap3_provider_manager' => $extensionClassesPath . 'class.tx_icsgmap3_provider_manager.php',
	'tx_icsgmap3_taglist_provider' => $extensionClassesPath . 'class.tx_icsgmap3_taglist_provider.php',
	'tx_icsgmap3_dynflex' => $extensionClassesPath . 'helpers/class.tx_icsgmap3_dynflex.php',
	'tx_icsgmap3_flexform_helper' => $extensionClassesPath . 'helpers/class.tx_icsgmap3_flexform_helper.php',
	'tx_icsgmap3_pi1' => $extensionPath . 'pi1/class.tx_icsgmap3_pi1.php',
	'tx_icsgmap3_pi1_wizicon' => $extensionPath . 'pi1/class.tx_icsgmap3_pi1_wizicon.php',
	'tx_icsgmap3_pi2' => $extensionPath . 'pi2/class.tx_icsgmap3_pi2.php',
	'tx_icsgmap3_pi2_wizicon' => $extensionPath . 'pi2/class.tx_icsgmap3_pi2_wizicon.php',
);
?>