<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-06-27 10:57

$extensionPath = t3lib_extMgm::extPath('pnf_gmap3_ttaddress_poi');
$extensionClassesPath = t3lib_extMgm::extPath('pnf_gmap3_ttaddress_poi') . 'classes/';
return array(
	'tx_pnfgmap3ttaddresspoi_provider' => $extensionClassesPath . 'class.tx_pnfgmap3ttaddresspoi_provider.php',
);
?>