<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2014-02-10 14:50

$extensionPath = t3lib_extMgm::extPath('ics_gmap3_levels');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_icsgmap3levels_provider' => $extensionClassesPath . 'class.tx_icsgmap3levels_provider.php',
	'tx_icsgmap3levels_tca' => $extensionClassesPath . 'class.tx_icgmap3levels_tca.php',
);
?>